In [7]:
#import modules 
from sklearn import datasets 
import numpy as np 
import pandas as pd 
from sklearn import linear_model

In [17]:
#loads Boston dataset from datasets 
data = datasets.load_boston() 

#define the data/predictors as the pre-set feature names 
df = pd.DataFrame(data.data, columns=data.feature_names)

#put the target (housing value --MEDV) in another DataFrame
target = pd.DataFrame(data.target, columns=["MEDV"])

In [18]:
data.target[:10]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9])

In [19]:
X = df 
y = target["MEDV"]

model = linear_model.LinearRegression()
model = model.fit(X,y)

In [20]:
#prediction
predictions = model.predict(X)
predictions[0:5]

array([30.00821269, 25.0298606 , 30.5702317 , 28.60814055, 27.94288232])

In [21]:
model.score(X,y)

0.7406077428649427

In [22]:
#coefficients forthe predictors
model.coef_

array([-1.07170557e-01,  4.63952195e-02,  2.08602395e-02,  2.68856140e+00,
       -1.77957587e+01,  3.80475246e+00,  7.51061703e-04, -1.47575880e+00,
        3.05655038e-01, -1.23293463e-02, -9.53463555e-01,  9.39251272e-03,
       -5.25466633e-01])

In [23]:
#intercept
model.intercept_

36.49110328036238